name: Bot CI-CD

on:
    push:
    branches: [development]
    pull_request:
    branches: [development]
    # Run this workflow manually from the Actions tab on Repo homepage
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  # VPS IP
                  host: ${{ secrets.VPS_SSH_HOST }}
                  
                  # VPS username
                  username: ${{ secrets.VPS_SSH_USERNAME }}
                  
                  # SSH key (copy it from your local machine)
                  key: ${{ secrets.VPS_SSH_SECRET }}
                  # SSH port
                  port: ${{ secrets.VPS_SSH_PORT }}
                  script: |
                      cd ${{ secrets.PROJECT_PATH }}
                      git pull origin development
                      make down
                      make build
                      echo "Deleting old image(s)..."
                      docker image prune -a -f